nlp_configuration:
  nlp_engine_name: stanza
  models:
    -
      lang_code: en
      model_name: en
    -
      lang_code: de
      model_name: de
    -
      lang_code: it
      model_name: it

  ner_model_configuration:
    model_to_presidio_entity_mapping:
      PER: PERSON
      PERSON: PERSON
      NORP: NRP
      FAC: LOCATION
      LOC: LOCATION
      LOCATION: LOCATION
      GPE: LOCATION
      ORG: ORGANIZATION
      ORGANIZATION: ORGANIZATION
      DATE: DATE_TIME
      TIME: DATE_TIME

    low_confidence_score_multiplier: 0.4
    low_score_entity_names:
    - ORGANIZATION # Has many false positives
    labels_to_ignore:
    - CARDINAL
    - EVENT
    - LANGUAGE
    - LAW
    - MONEY
    - ORDINAL
    - PERCENT
    - PRODUCT
    - QUANTITY
    - WORK_OF_ART
    - NRP
    - DATE_TIME