name: CI with Cached NLP Models

on:
  push:
    paths:
      - "processing/**"
  pull_request:
    paths:
      - "processing/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: processing/environment.yaml
          auto-activate-base: false
          activate-environment: guard-env
          python-version: "3.11"
          miniforge-variant: Miniforge3
          update-conda: true  # Ensure the environment is up-to-date

      - name: Verify Conda Environment
        run: conda info --envs

      - name: Cache NLP models (spaCy, Flair, HuggingFace)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/huggingface
            ~/.cache/torch
            ~/.cache/flair
            ~/.cache/spacy
          key: ${{ runner.os }}-nlp-models-v1

      - name: Run GUARD cli unit test
        working-directory: processing
        run: pytest tests/unit/test_guard_cli.py